
export const WEATHER_CODES: { [key: number]: { description: string; icon: string } } = {
  0: { description: 'Clear sky', icon: 'fa-sun' },
  1: { description: 'Mainly clear', icon: 'fa-cloud-sun' },
  2: { description: 'Partly cloudy', icon: 'fa-cloud' },
  3: { description: 'Overcast', icon: 'fa-smog' },
  45: { description: 'Fog', icon: 'fa-smog' },
  48: { description: 'Depositing rime fog', icon: 'fa-smog' },
  51: { description: 'Light drizzle', icon: 'fa-cloud-rain' },
  53: { description: 'Moderate drizzle', icon: 'fa-cloud-rain' },
  55: { description: 'Dense drizzle', icon: 'fa-cloud-showers-heavy' },
  56: { description: 'Light freezing drizzle', icon: 'fa-snowflake' },
  57: { description: 'Dense freezing drizzle', icon: 'fa-snowflake' },
  61: { description: 'Slight rain', icon: 'fa-cloud-rain' },
  63: { description: 'Moderate rain', icon: 'fa-cloud-showers-heavy' },
  65: { description: 'Heavy rain', icon: 'fa-cloud-showers-heavy' },
  66: { description: 'Light freezing rain', icon: 'fa-snowflake' },
  67: { description: 'Heavy freezing rain', icon: 'fa-snowflake' },
  71: { description: 'Slight snow fall', icon: 'fa-snowflake' },
  73: { description: 'Moderate snow fall', icon: 'fa-snowflake' },
  75: { description: 'Heavy snow fall', icon: 'fa-snowflake' },
  77: { description: 'Snow grains', icon: 'fa-snowflake' },
  80: { description: 'Slight rain showers', icon: 'fa-cloud-showers-heavy' },
  81: { description: 'Moderate rain showers', icon: 'fa-cloud-showers-heavy' },
  82: { description: 'Violent rain showers', icon: 'fa-cloud-showers-heavy' },
  85: { description: 'Slight snow showers', icon: 'fa-snowflake' },
  86: { description: 'Heavy snow showers', icon: 'fa-snowflake' },
  95: { description: 'Thunderstorm', icon: 'fa-bolt' },
  96: { description: 'Thunderstorm with slight hail', icon: 'fa-bolt' },
  99: { description: 'Thunderstorm with heavy hail', icon: 'fa-bolt' },
};
